### ISSUE TITLE
cross compilation issue 

### ISSUE THREAD

**Issue by sharathbaddam** [zeromq/zeromq.js#125]
Hi,
I'm trying to cross compile for linux ArmV7(32 bit) on a linux 64 bit machine, but i'm getting this error. Any help is appreciated. 

```
> node scripts/preinstall.js

Building libzmq for linux
configure: loading site script /usr/local/slp-redwolf-x86_64/site-config-cortexa8hf-vfp-neon-oe-linux-gnueabi
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking how to create a ustar tar archive... gnutar
checking whether make supports nested variables... yes
checking for gcc... arm-oe-linux-gnueabi-gcc  -march=armv7-a -marm  -mthumb-interwork -mfloat-abi=hard -mfpu=neon -mtune=cortex-a8 --sysroot=/usr/local/slp-redwolf-x86_64/sysroots/cortexa8hf-vfp-neon-oe-linux-gnueabi
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... configure: error: in `/home/test/linux-arm/zmqtest/node_modules/zeromq/zmq/zeromq-4.1.6':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details
child process exited with code 1
make: Entering directory `/home/test/linux-arm/zmqtest/node_modules/zeromq/build'
  CXX(target) Release/obj.target/zmq/binding.o
  SOLINK_MODULE(target) Release/obj.target/zmq.node
arm-oe-linux-gnueabi-g++: error: ./Release/../../zmq/lib/libzmq.a: No such file or directory
make: *** [Release/obj.target/zmq.node] Error 1
make: Leaving directory `/home/test/linux-arm/zmqtest/node_modules/zeromq/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 3.13.0-24-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/test/linux-arm/zmqtest/node_modules/zeromq
gyp ERR! node -v v6.9.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
```

**Comment by rgbkrk** [comment]
Seems like the libzmq install didn't happen or needs to be fixed up. Sadly I can't be more help than that right now.

**Comment by sharathbaddam** [comment]
Hello,

We were able to get cross compilation to work on a cloned copy by adding an environment variable in script/build_libzmq.sh and setting the env properly to include a --host.   We hope something like this can be added but wanted you to check this idea or add something equal or better to address cross compilation.

Can this be done? Or should we submit a pull request?


 
In build_libzmq.sh

```
if [ "$ZMQ" = "4.1.6" ]; then
  ./configure "--prefix=${ZMQ_PREFIX}" --with-relaxed --enable-static --disable-shared --without-documentation ${ZMQJS_OPTIONS} ;
else

  ./configure "--prefix=${ZMQ_PREFIX}" --disable-pedantic --enable-static --disable-shared --without-docs ${ZMQJS_OPTIONS} ;
fi
```

in our build script
``
export ZMQJS_OPTIONS="--host= <host stuff>"
``

**Comment by interpretor** [comment]
This should be solved now
