### ISSUE TITLE
prebuild-install || (npm run build:libzmq && node-gyp rebuild) failed on centos 6.7

### ISSUE THREAD

**Issue by NextZeus** [zeromq/zeromq.js#129]
```
make: *** [Release/obj.target/zmq/binding.o] Error 1
make: Leaving directory `/home/node/node_modules/zeromq/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 2.6.32-573.7.1.el6.x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/node/node_modules/zeromq
gyp ERR! node -v v4.4.5
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok
npm ERR! zeromq@4.2.0 install: `prebuild-install || (npm run build:libzmq && node-gyp rebuild)`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zeromq@4.2.0 install script.
npm ERR! This is most likely a problem with the zeromq package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     prebuild-install || (npm run build:libzmq && node-gyp rebuild)
npm ERR! You can get their info via:
npm ERR!     npm owner ls zeromq
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 2.6.32-573.7.1.el6.x86_64
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "i" "zeromq"
npm ERR! cwd /home/node
npm ERR! node -v v4.4.5
npm ERR! npm -v 1.4.3
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/node/npm-debug.log
npm ERR! not ok code 0
```

**Comment by lgeiger** [comment]
I looks like it fails to download the prebuilt binaries and then tries to [build from source](https://github.com/zeromq/zeromq.js#installation---from-source) which like fails due to missing dependencies.

Could you post the entire log?

**Comment by NextZeus** [comment]
I have found the problem, my centos  g++ version was 4.7 , and i search google , upgrade g++version

https://github.com/nodejs/node-gyp/issues/940

**Comment by rgbkrk** [comment]
Great!
