### ISSUE TITLE
Packaging with electron, rebuild cannot find zmq binaries/headers

### ISSUE THREAD

**Issue by spennihana** [zeromq/zeromq.js#171]
#### version info:

```
mb:web spencer$ npm --version
3.10.10
mb:web spencer$ node --version
v6.11.1
mb:web spencer$ electron --version
v1.6.11
mb:web spencer$ electron-forge --version
✔ Checking your system
3.0.5

```

I'm brand-new to the wonderful world of node, and I spent a few hours with this yesterday.

##### npm install
Ok so I've installed the zeromq using npm like so:
```
mb:web spencer$ npm install zeromq --save

> zeromq@4.5.0 install /Users/spencer/RicePlate/MyPkg/web/node_modules/zeromq
> node scripts/prebuild-install.js || (npm run build:libzmq && node-gyp rebuild)


prebuild-install info begin Prebuild-install version 2.2.2
prebuild-install info looking for local prebuild @ prebuilds/zeromq-v4.5.0-node-v48-darwin-x64.tar.gz
prebuild-install info looking for cached prebuild @ /Users/spencer/.npm/_prebuilds/https-github.com-zeromq-zeromq.js-releases-download-v4.5.0-zeromq-v4.5.0-node-v48-darwin-x64.tar.gz
prebuild-install info found cached prebuild 
prebuild-install info unpacking @ /Users/spencer/.npm/_prebuilds/https-github.com-zeromq-zeromq.js-releases-download-v4.5.0-zeromq-v4.5.0-node-v48-darwin-x64.tar.gz
prebuild-install info unpack resolved to /Users/spencer/RicePlate/MyPkg/web/node_modules/zeromq/build/Release/zmq.node
prebuild-install info unpack required /Users/spencer/RicePlate/MyPkg/web/node_modules/zeromq/build/Release/zmq.node successfully
prebuild-install info install Successfully installed prebuilt binary!

MyPkg@1.0.0 /Users/spencer/RicePlate/MyPkg/web
├── UNMET PEER DEPENDENCY eslint-plugin-jsx-a11y@6.0.2 invalid
└── zeromq@4.5.0 

npm WARN eslint-config-airbnb@15.1.0 requires a peer of eslint-plugin-jsx-a11y@^5.1.1 but none was installed.
```
Maybe orthogonal issue: Is this eslint warning a problem (i'm ignoring it _for now_).

#### inspect node_modules/zeromq
zeromq appears in `node_modules/`, but upon inspection there ain't no zmq binaries:

```
mb:zeromq spencer$ ls -la
total 200
drwxr-xr-x   20 spencer  staff    680 Aug 13 12:22 .
drwxr-xr-x  579 spencer  staff  19686 Aug 13 12:22 ..
-rw-r--r--    1 spencer  staff    173 Dec  5  2016 .editorconfig
-rw-r--r--    1 spencer  staff    324 Dec  3  2016 .npmignore
-rw-r--r--    1 spencer  staff   3079 Jul  2 15:43 .travis.yml
-rw-r--r--    1 spencer  staff   5820 Dec  5  2016 History.md
-rw-r--r--    1 spencer  staff   1098 Dec  5  2016 LICENSE
-rw-r--r--    1 spencer  staff   7769 Jul  2 15:43 README.md
-rw-r--r--    1 spencer  staff    975 Dec 11  2016 appveyor.yml
-rw-r--r--    1 spencer  staff  46559 Jun  1 08:47 binding.cc
-rw-r--r--    1 spencer  staff   1120 Dec  5  2016 binding.gyp
drwxr-xr-x    3 spencer  staff    102 Aug 13 12:22 build
-rw-r--r--    1 spencer  staff    169 Dec  5  2016 codecov.yml
drwxr-xr-x    7 spencer  staff    238 Aug 13 12:22 examples
-rw-r--r--    1 spencer  staff     35 Dec  5  2016 index.js
drwxr-xr-x    3 spencer  staff    102 Jun 25 15:25 lib
-rw-r--r--    1 spencer  staff   3121 Aug 13 12:22 package.json
drwxr-xr-x    9 spencer  staff    306 Aug 13 12:22 scripts
drwxr-xr-x   26 spencer  staff    884 Aug 13 12:22 test
drwxr-xr-x    3 spencer  staff    102 Dec  5  2016 windows
mb:zeromq spencer$ find . -name '*libzmq*'
./scripts/build_libzmq.sh
mb:zeromq spencer$ find . -name '*zmq*'
./build/Release/zmq.node
./scripts/build_libzmq.sh
./test/zmq_proxy.js
./test/zmq_proxy.push-pull.js
./test/zmq_proxy.router-dealer.js
./test/zmq_proxy.xpub-xsub.js
./test/zmq_proxy.xrep-xreq.js
./windows/include/zmq.h
./windows/include/zmq_utils.h
```

### I.e. there's no `zmq` directory 😢 

Did I miss a step here? Is this expected state of things after `npm install zeromq`?

### electron-forge package/make

Now when it comes time to build my electron package it doesn't have the prebuilt zmq binaries or headers, so of course the electron-forge package goes down in flames with:

```
Failed with exit code: 1
Error: gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@6.11.1 | darwin | x64
gyp info spawn /Library/Frameworks/Python.framework/Versions/2.7/bin/python2
gyp info spawn args [ '/usr/local/lib/node_modules/electron-forge/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/private/var/folders/d5/7ynz8gm165q4b37kmvnhglfw0000gn/T/electron-packager/darwin-x64/MyPkg-darwin-x64/Electron.app/Contents/Resources/app/node_modules/zeromq/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/electron-forge/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/spencer/.electron-gyp/.node-gyp/iojs-1.6.11/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/spencer/.electron-gyp/.node-gyp/iojs-1.6.11',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/electron-forge/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/spencer/.electron-gyp/.node-gyp/iojs-1.6.11/<(target_arch)/iojs.lib',
gyp info spawn args   '-Dmodule_root_dir=/private/var/folders/d5/7ynz8gm165q4b37kmvnhglfw0000gn/T/electron-packager/darwin-x64/MyPkg-darwin-x64/Electron.app/Contents/Resources/app/node_modules/zeromq',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/zmq/binding.o
../binding.cc:28:10: fatal error: 'zmq.h' file not found
#include <zmq.h>
         ^
1 error generated.
make[1]: *** [Release/obj.target/zmq/binding.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/electron-forge/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 15.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/electron-forge/node_modules/.bin/node-gyp" "rebuild" "--target=1.6.11" "--arch=x64" "--dist-url=https://atom.io/download/electron" "--build-from-source"
gyp ERR! cwd /private/var/folders/d5/7ynz8gm165q4b37kmvnhglfw0000gn/T/electron-packager/darwin-x64/MyPkg-darwin-x64/Electron.app/Contents/Resources/app/node_modules/zeromq
gyp ERR! node -v v6.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
```

### hack/work-around

Basically what I did was take the zeromq/package.json and forced it to build the zmq directory if it wasn't there by adding a `preinstall` directive to the `"scripts"` section:

```
  "scripts": {
    "build:docs": "jsdoc -R README.md -d docs lib/*.js",
    "build:libzmq": "node scripts/preinstall.js",
    "preinstall": "node scripts/preinstall.js",     <------ RIGHT HERE
    "coverage": "nyc report --reporter=text-lcov > coverage/lcov.info",
    "install": "node scripts/prebuild-install.js || (npm run build:libzmq && node-gyp rebuild)",
    "postpublish": "./scripts/trigger_travis_build.sh",
    "prebuild": "prebuild --all --strip",
    "precoverage": "nyc npm run test",
    "test": "mocha --expose-gc --slow 300",
    "test:electron": "electron-mocha --slow 300"
  },
```

And I save this module off to the side as a now-static component of my project 😢 . My package.json has a dependencies section that looks like this:
```
  "dependencies": {
    "electron-compile": "^6.4.1",
    "zeromq": "file:zeromq"
  },
```

I badly need to be straightened out! Hopefully someone can help!

**Comment by interpretor** [comment]
Hi and welcome to node.js!

> Maybe orthogonal issue: Is this eslint warning a problem (i'm ignoring it for now).

 This is because the airbnb javascript lib needs some additional packages. On OS X/Linux, just exec:
```
(
  export PKG=eslint-config-airbnb;
  npm info "$PKG@latest" peerDependencies --json | command sed 's/[\{\},]//g ; s/: /@/g' | xargs npm install --save-dev "$PKG@latest"
)
```
(Source: https://www.npmjs.com/package/eslint-config-airbnb)

> I.e. there's no zmq directory 😢

The binary is there, under `./build/Release/zmq.node`. So the installation of the module worked fine.

I cannot solve your electron problem for now without diving into this problem, as I don't use electron. Maybe @lgeiger or @rgbkrk can help you out.

**Comment by rgbkrk** [comment]
electron forge is uncharted territory for me. We use https://github.com/electron-userland/electron-builder which acknowledges prebuilds, including zeromq.

**Comment by lgeiger** [comment]
If there's a way to force `electron-forge` to omit the `--build-from-source` flag when rebuilding, everything should work fine (just guessing from the error message, I haven't used it).

Otherwise you could try installing zeromq using `npm install zeromq --build-from-source`. Then you won't get the benefits of prebuilt binaries but you'll have the `zmq` folder so a rebuild from `electron-forge` shouldn't fail.

**Comment by lgeiger** [comment]
For more information about the struggle with native modules in Electron, take a look at https://electron.atom.io/docs/tutorial/using-native-node-modules/

**Comment by reqshark** [comment]
electron tends to superficially set different ABI versions than node native runtime, so recalibrate the ABI numbers when installing native modules for use in Electron's runtime:

```bash
npm install
npm rebuild --runtime=electron --target=1.4.12 --disturl=https://atom.io/download/atom-shell --abi=51
```

**Comment by madCoder24** [comment]
I noticed similar build issues when running 'electron-rebuild'. I am only using zyre.js, but when running 'electron-rebuild' it grabs it from the dependency tree so the rebuild fails. It does work when using 'npm rebuild' with a runtime of electron. So it might not be an issue, per say, but I just wanted to note it here as this issue seemed relevant to what I had experienced.

**Comment by aminya** [comment]
v6 was released. Please try again with the latest version, and report back if the issue still persists.
https://github.com/zeromq/zeromq.js/releases/tag/v6.0.0
