### ISSUE TITLE
FreeBSD support

### ISSUE THREAD

**Issue by tsgan** [zeromq/zeromq.js#195]
Please add -I/usr/local/include to CFLAGS.
When I try to install zeromq using npm install, it gives:

```
gmake: Entering directory '/usr/home/tsgan/education/LFS171x/sawtooth-material/sawtooth-tuna/processor/node_modules/zeromq/build'
  CXX(target) Release/obj.target/zmq/binding.o
../binding.cc:28:10: fatal error: 'zmq.h' file not found
#include <zmq.h>
         ^~~~~~~
1 error generated.
gmake: *** [zmq.target.mk:92: Release/obj.target/zmq/binding.o] Error 1
gmake: Leaving directory '/usr/home/tsgan/education/LFS171x/sawtooth-material/sawtooth-tuna/processor/node_modules/zeromq/build'
gyp ERR! build error
gyp ERR! stack Error: `gmake` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System FreeBSD 11.1-STABLE
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/home/tsgan/education/LFS171x/sawtooth-material/sawtooth-tuna/processor/node_modules/zeromq
gyp ERR! node -v v6.11.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm ERR! FreeBSD 11.1-STABLE
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "zeromq" "--zmq-external"
npm ERR! node v6.11.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
```

**Comment by tsgan** [comment]
Actually binding.gyp needs:

```
        ['OS=="openbsd" or OS=="freebsd"', {
          'include_dirs': [
            '<!@(pkg-config libzmq --cflags-only-I | sed s/-I//g)',
            '/usr/local/include',
          ],
          'libraries': [
            '<!@(pkg-config libzmq --libs)',
            '-L/usr/local/lib',
          ]
        }],
```

**Comment by rolftimmermans** [comment]
FreeBSD is supported but since we don't run it in CI it is difficult to guarantee it is working or to provide prebuilt binaries. Note thought that if you want to link against a shared library you should build with `--zmq-shared` or with the environment variable `npm_config_zmq_shared=true`.

Please open an issue if you run into any problems.
