### ISSUE TITLE
ZeroMQ build with electron throws error

### ISSUE THREAD

**Issue by sona15** [zeromq/zeromq.js#203]
I have installed zeromq using > **_npm install zeromq_**
Then I ran this manually > 
**_npm rebuild zeromq --runtime=electron --target=1.7.6_**
When I start my electron app with command> **_npm run electron:serve_** 
I get the follwoing error:

App threw an error during load
Error: **The system cannot find message text for message number 0x%1 in the messag
e file for %2**.
\\?\C:\Users\\17-11-17\dist\node_modules\zeromq\build\Release\zmq.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)

    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\17-11-17\dist\node_modules\zeromq\lib\index.js:6:11)
    at Object.<anonymous> (C:\Users\17-11-17\dist\node_modules\zeromq\lib\index.js:848:3)

**Comment by vincentEuloge** [comment]
Do you have the same problem if you specify the architecture and the platform ?
ie: npm rebuild zeromq --runtime=electron --target=1.7.6 --platform=win32 --arch=x64

**Comment by aminya** [comment]
v6 was released. Please try again with the latest version, and report back if the issue still persists.
https://github.com/zeromq/zeromq.js/releases/tag/v6.0.0
