### ISSUE TITLE
windows npm install zeromq failed.

### ISSUE THREAD

**Issue by daishenghao** [zeromq/zeromq.js#238]
env:
node -v: 8.9.4
npm -v: 5.6.0
windows 10 64bit

use npm to install zeromq: 
`npm install zeromq`

**then failed, error info as follows（use *** instead of privated info）:**
```

prebuild-install info begin Prebuild-install version 2.5.1
prebuild-install info looking for local prebuild @ prebuilds\zeromq-v4.6.0-node-v57-win32-x64.tar.gz
prebuild-install info looking for cached prebuild @ C:\Users\*****\AppData\Roaming\npm-cache\_prebuilds\https-github
.com-zeromq-zeromq.js-releases-download-v4.6.0-zeromq-v4.6.0-node-v57-win32-x64.tar.gz
prebuild-install http request GET https://github.com/zeromq/zeromq.js/releases/download/v4.6.0/zeromq-v4.6.0-node-v5
7-win32-x64.tar.gz
prebuild-install WARN install connect ECONNREFUSED 121.59.17.8:443

Downloading libzmq for Windows
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 121.59.17.8:443
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
npm WARN express-ws@3.0.0 requires a peer of express@^4.0.0 || ^5.0.0-alpha.1 but none is installed. You must instal
l peer dependencies yourself.
npm WARN ****@1.0.0 No description
npm WARN ****@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zeromq@4.6.0 install: `node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)
`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zeromq@4.6.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

**Comment by daishenghao** [comment]
Sorry, then I find it that It's my windows hosts file cause it.
