### ISSUE TITLE
Flaky tests

### ISSUE THREAD

**Issue by BridgeAR** [zeromq/zeromq.js#253]
Running the tests some times results in a failure such as:

```
   1) socket.monitor should use default interval and numOfEvents:
      Uncaught AssertionError: expected NaN to be within 9..20
       at Assertion.fail (node_modules/should/cjs/should.js:265:17)
       at Assertion.value [as within] (node_modules/should/cjs/should.js:340:19)
       at exports.Socket.<anonymous> (test/socket.monitor.js:83:22)
       at Object.self._zmq.onMonitorEvent (lib/index.js:543:12)
```

See 
https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/1418/nodes=ubuntu1404-64/testReport/junit/(root)/citgm/zeromq_v4_6_0/

This seems to be a race condition in the test itself. It would be nice to have a confirmation for this and is there a way to make the test more reliable?

**Comment by rolftimmermans** [comment]
This test has been replaced by newer tests in the master branch so this should no longer be an issue going forward.
