### ISSUE TITLE
Unable to install on CentOS 7.6

### ISSUE THREAD

**Issue by ezze** [zeromq/zeromq.js#365]
**Describe the bug**

Trying to install `zeromq@6.0.0-beta.4` but the installation fails during the build.

**Reproducing**

```
[handler@node01 zeromq-install-test]$ rpm -q centos-release
centos-release-7-6.1810.2.el7.centos.x86_64
[handler@node01 zeromq-install-test]$ uname -ismporv
Linux 3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
[handler@node01 zeromq-install-test]$ sudo yum install cmake
...
Complete!
[handler@node01 zeromq-install-test]$ yarn add zeromq@6.0.0-beta.4
yarn add v1.19.1
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
error /home/handler/zeromq-install-test/node_modules/zeromq: Command failed.
Exit code: 1
Command: node-gyp-build
Arguments: 
Directory: /home/handler/zeromq-install-test/node_modules/zeromq
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.3
gyp info using node@10.17.0 | linux | x64
gyp info find Python using Python version 2.7.5 found at "/usr/bin/python"
gyp info spawn /usr/bin/python
gyp info spawn args [ '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/handler/zeromq-install-test/node_modules/zeromq/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/handler/.cache/node-gyp/10.17.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/handler/.cache/node-gyp/10.17.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/handler/.cache/node-gyp/10.17.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/handler/zeromq-install-test/node_modules/zeromq',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory `/home/handler/zeromq-install-test/node_modules/zeromq/build'
  ACTION binding_gyp_libzmq_target_build_libzmq libzmq/lib
Downloading libzmq source...
Building libzmq...
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Detected ZMQ Version - 4.3.2
-- Performing Test COMPILER_SUPPORTS_CXX11
-- Performing Test COMPILER_SUPPORTS_CXX11 - Success
-- Performing Test COMPILER_SUPPORTS_C11
-- Performing Test COMPILER_SUPPORTS_C11 - Success
-- Performing Test CXX_HAS_TAUT_WARNING
-- Performing Test CXX_HAS_TAUT_WARNING - Success
-- Performing Test CC_HAS_TAUT_WARNING
-- Performing Test CC_HAS_TAUT_WARNING - Success
-- Using tweetnacl for CURVE security
-- Looking for kqueue
-- Looking for kqueue - not found
-- Looking for epoll_create
-- Looking for epoll_create - found
-- Looking for epoll_create1
-- Looking for epoll_create1 - found
-- Using polling method in I/O threads: epoll
-- Using polling method in zmq_poll(er)_* API: poll
-- Using 64 bytes alignment for lock-free data structures
-- Looking for include file windows.h
-- Looking for include file windows.h - not found
-- Looking for include file condition_variable
-- Looking for include file condition_variable - not found
-- Using condition_variable_t implementation: pthreads
-- Looking for include file ifaddrs.h
-- Looking for include file ifaddrs.h - found
-- Looking for include file sys/uio.h
-- Looking for include file sys/uio.h - found
-- Looking for include file sys/eventfd.h
-- Looking for include file sys/eventfd.h - found
-- Checking whether EFD_CLOEXEC is supported
-- Performing Test ZMQ_HAVE_EVENTFD_CLOEXEC
-- Performing Test ZMQ_HAVE_EVENTFD_CLOEXEC - Success
-- Looking for SO_PEERCRED
-- Looking for SO_PEERCRED - found
-- Looking for LOCAL_PEERCRED
-- Looking for LOCAL_PEERCRED - not found
-- Looking for clock_gettime
-- Looking for clock_gettime - found
-- Looking for fork
-- Looking for fork - found
-- Looking for gethrtimei
-- Looking for gethrtimei - not found
-- Looking for mkdtemp
-- Looking for mkdtemp - found
-- Looking for accept4
-- Looking for accept4 - found
-- Looking for strnlen
-- Looking for strnlen - found
-- Performing Test HAVE_FLAG_-Wall
-- Performing Test HAVE_FLAG_-Wall - Failed
-- Performing Test HAVE_FLAG_-Wextra
-- Performing Test HAVE_FLAG_-Wextra - Failed
-- Performing Test HAVE_FLAG_-Wno-long-long
-- Performing Test HAVE_FLAG_-Wno-long-long - Failed
-- Performing Test HAVE_FLAG_-Wno-uninitialized
-- Performing Test HAVE_FLAG_-Wno-uninitialized - Failed
-- Performing Test HAVE_FLAG_-pedantic
-- Performing Test HAVE_FLAG_-pedantic - Failed
-- Checking whether noexcept is supported
-- Performing Test ZMQ_HAVE_NOEXCEPT
-- Performing Test ZMQ_HAVE_NOEXCEPT - Success
-- Checking whether SOCK_CLOEXEC is supported
-- Performing Test ZMQ_HAVE_SOCK_CLOEXEC
-- Performing Test ZMQ_HAVE_SOCK_CLOEXEC - Success
-- Checking whether O_CLOEXEC is supported
-- Performing Test ZMQ_HAVE_O_CLOEXEC
-- Performing Test ZMQ_HAVE_O_CLOEXEC - Success
-- Checking whether SO_BINDTODEVICE is supported
-- Performing Test ZMQ_HAVE_SO_BINDTODEVICE
-- Performing Test ZMQ_HAVE_SO_BINDTODEVICE - Success
-- Checking whether SO_KEEPALIVE is supported
-- Performing Test ZMQ_HAVE_SO_KEEPALIVE
-- Performing Test ZMQ_HAVE_SO_KEEPALIVE - Success
-- Checking whether TCP_KEEPCNT is supported
-- Performing Test ZMQ_HAVE_TCP_KEEPCNT
-- Performing Test ZMQ_HAVE_TCP_KEEPCNT - Success
-- Checking whether TCP_KEEPIDLE is supported
-- Performing Test ZMQ_HAVE_TCP_KEEPIDLE
-- Performing Test ZMQ_HAVE_TCP_KEEPIDLE - Success
-- Checking whether TCP_KEEPINTVL is supported
-- Performing Test ZMQ_HAVE_TCP_KEEPINTVL
-- Performing Test ZMQ_HAVE_TCP_KEEPINTVL - Success
-- Checking whether TCP_KEEPALIVE is supported
-- Performing Test ZMQ_HAVE_TCP_KEEPALIVE
-- Performing Test ZMQ_HAVE_TCP_KEEPALIVE - Failed
-- Checking whether TIPC is supported
-- Performing Test ZMQ_HAVE_TIPC
-- Performing Test ZMQ_HAVE_TIPC - Success
-- Checking pthread_setname signature
-- Performing Test ZMQ_HAVE_PTHREAD_SETNAME_1
-- Performing Test ZMQ_HAVE_PTHREAD_SETNAME_1 - Failed
-- Performing Test ZMQ_HAVE_PTHREAD_SETNAME_2
-- Performing Test ZMQ_HAVE_PTHREAD_SETNAME_2 - Success
-- Performing Test ZMQ_HAVE_PTHREAD_SETNAME_3
-- Performing Test ZMQ_HAVE_PTHREAD_SETNAME_3 - Failed
-- Performing Test ZMQ_HAVE_PTHREAD_SET_NAME
-- Performing Test ZMQ_HAVE_PTHREAD_SET_NAME - Failed
-- Checking pthread_setaffinity signature
-- Performing Test ZMQ_HAVE_PTHREAD_SETAFFINITY
-- Performing Test ZMQ_HAVE_PTHREAD_SETAFFINITY - Success
-- Checking whether getrandom is supported
-- Performing Test ZMQ_HAVE_GETRANDOM
-- Performing Test ZMQ_HAVE_GETRANDOM - Failed
-- Could NOT find AsciiDoc (missing:  ASCIIDOC_EXECUTABLE) 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/handler/zeromq-install-test/node_modules/zeromq/build/libzmq
gmake[1]: Entering directory `/home/handler/zeromq-install-test/node_modules/zeromq/build/libzmq'
gmake[2]: Entering directory `/home/handler/zeromq-install-test/node_modules/zeromq/build/libzmq'
gmake[3]: Entering directory `/home/handler/zeromq-install-test/node_modules/zeromq/build/libzmq'
Scanning dependencies of target objects
gmake[3]: Leaving directory `/home/handler/zeromq-install-test/node_modules/zeromq/build/libzmq'
gmake[3]: Entering directory `/home/handler/zeromq-install-test/node_modules/zeromq/build/libzmq'
[  1%] [  2%] [  3%] [  4%] [  5%] Building C object CMakeFiles/objects.dir/src/tweetnacl.c.o
Building CXX object CMakeFiles/objects.dir/src/precompiled.cpp.o
Building CXX object CMakeFiles/objects.dir/src/address.cpp.o
Building CXX object CMakeFiles/objects.dir/src/client.cpp.o
Building CXX object CMakeFiles/objects.dir/src/clock.cpp.o
[  6%] Building CXX object CMakeFiles/objects.dir/src/ctx.cpp.o
[  7%] Building CXX object CMakeFiles/objects.dir/src/curve_mechanism_base.cpp.o
[  8%] Building CXX object CMakeFiles/objects.dir/src/curve_client.cpp.o
[  9%] Building CXX object CMakeFiles/objects.dir/src/curve_server.cpp.o
[ 10%] Building CXX object CMakeFiles/objects.dir/src/dealer.cpp.o
[ 11%] Building CXX object CMakeFiles/objects.dir/src/devpoll.cpp.o
[ 12%] Building CXX object CMakeFiles/objects.dir/src/dgram.cpp.o
[ 13%] Building CXX object CMakeFiles/objects.dir/src/dist.cpp.o
[ 14%] Building CXX object CMakeFiles/objects.dir/src/endpoint.cpp.o
[ 15%] Building CXX object CMakeFiles/objects.dir/src/epoll.cpp.o
[ 16%] Building CXX object CMakeFiles/objects.dir/src/err.cpp.o
[ 17%] Building CXX object CMakeFiles/objects.dir/src/fq.cpp.o
[ 18%] Building CXX object CMakeFiles/objects.dir/src/io_object.cpp.o
[ 19%] Building CXX object CMakeFiles/objects.dir/src/io_thread.cpp.o
[ 20%] Building CXX object CMakeFiles/objects.dir/src/ip.cpp.o
[ 21%] Building CXX object CMakeFiles/objects.dir/src/ipc_address.cpp.o
[ 22%] Building CXX object CMakeFiles/objects.dir/src/ipc_connecter.cpp.o
[ 23%] [ 24%] Building CXX object CMakeFiles/objects.dir/src/kqueue.cpp.o
Building CXX object CMakeFiles/objects.dir/src/ipc_listener.cpp.o
[ 25%] Building CXX object CMakeFiles/objects.dir/src/lb.cpp.o
[ 26%] Building CXX object CMakeFiles/objects.dir/src/mailbox.cpp.o
[ 27%] Building CXX object CMakeFiles/objects.dir/src/mailbox_safe.cpp.o
[ 28%] [ 29%] Building CXX object CMakeFiles/objects.dir/src/mechanism.cpp.o
Building CXX object CMakeFiles/objects.dir/src/mechanism_base.cpp.o
[ 30%] Building CXX object CMakeFiles/objects.dir/src/metadata.cpp.o
[ 31%] Building CXX object CMakeFiles/objects.dir/src/msg.cpp.o
[ 32%] Building CXX object CMakeFiles/objects.dir/src/mtrie.cpp.o
[ 33%] [ 34%] Building CXX object CMakeFiles/objects.dir/src/norm_engine.cpp.o
Building CXX object CMakeFiles/objects.dir/src/object.cpp.o
[ 35%] Building CXX object CMakeFiles/objects.dir/src/options.cpp.o
[ 36%] Building CXX object CMakeFiles/objects.dir/src/own.cpp.o
[ 37%] Building CXX object CMakeFiles/objects.dir/src/null_mechanism.cpp.o
[ 38%] Building CXX object CMakeFiles/objects.dir/src/pair.cpp.o
[ 39%] Building CXX object CMakeFiles/objects.dir/src/pgm_receiver.cpp.o
[ 40%] Building CXX object CMakeFiles/objects.dir/src/pgm_sender.cpp.o
[ 41%] [ 42%] Building CXX object CMakeFiles/objects.dir/src/pgm_socket.cpp.o
Building CXX object CMakeFiles/objects.dir/src/pipe.cpp.o
[ 43%] Building CXX object CMakeFiles/objects.dir/src/plain_client.cpp.o
[ 44%] Building CXX object CMakeFiles/objects.dir/src/plain_server.cpp.o
[ 45%] [ 46%] Building CXX object CMakeFiles/objects.dir/src/poll.cpp.o
Building CXX object CMakeFiles/objects.dir/src/poller_base.cpp.o
[ 47%] Building CXX object CMakeFiles/objects.dir/src/polling_util.cpp.o
[ 48%] Building CXX object CMakeFiles/objects.dir/src/pollset.cpp.o
[ 49%] Building CXX object CMakeFiles/objects.dir/src/proxy.cpp.o
[ 50%] Building CXX object CMakeFiles/objects.dir/src/pub.cpp.o
[ 51%] Building CXX object CMakeFiles/objects.dir/src/pull.cpp.o
[ 52%] Building CXX object CMakeFiles/objects.dir/src/push.cpp.o
[ 53%] Building CXX object CMakeFiles/objects.dir/src/random.cpp.o
[ 54%] Building CXX object CMakeFiles/objects.dir/src/raw_encoder.cpp.o
[ 55%] Building CXX object CMakeFiles/objects.dir/src/raw_decoder.cpp.o
[ 56%] [ 57%] Building CXX object CMakeFiles/objects.dir/src/reaper.cpp.o
Building CXX object CMakeFiles/objects.dir/src/rep.cpp.o
[ 58%] Building CXX object CMakeFiles/objects.dir/src/req.cpp.o
[ 59%] Building CXX object CMakeFiles/objects.dir/src/router.cpp.o
[ 60%] Building CXX object CMakeFiles/objects.dir/src/select.cpp.o
[ 61%] [ 62%] Building CXX object CMakeFiles/objects.dir/src/server.cpp.o
Building CXX object CMakeFiles/objects.dir/src/session_base.cpp.o
[ 63%] Building CXX object CMakeFiles/objects.dir/src/signaler.cpp.o
[ 64%] Building CXX object CMakeFiles/objects.dir/src/socket_base.cpp.o
[ 65%] Building CXX object CMakeFiles/objects.dir/src/socks.cpp.o
[ 66%] Building CXX object CMakeFiles/objects.dir/src/socks_connecter.cpp.o
[ 67%] Building CXX object CMakeFiles/objects.dir/src/stream.cpp.o
[ 68%] Building CXX object CMakeFiles/objects.dir/src/stream_engine.cpp.o
[ 69%] [ 70%] [ 71%] Building CXX object CMakeFiles/objects.dir/src/sub.cpp.o
Building CXX object CMakeFiles/objects.dir/src/tcp.cpp.o
Building CXX object CMakeFiles/objects.dir/src/tcp_address.cpp.o
[ 72%] Building CXX object CMakeFiles/objects.dir/src/tcp_connecter.cpp.o
[ 73%] Building CXX object CMakeFiles/objects.dir/src/tcp_listener.cpp.o
[ 74%] Building CXX object CMakeFiles/objects.dir/src/thread.cpp.o
[ 75%] Building CXX object CMakeFiles/objects.dir/src/trie.cpp.o
[ 76%] Building CXX object CMakeFiles/objects.dir/src/radix_tree.cpp.o
[ 77%] Building CXX object CMakeFiles/objects.dir/src/v1_decoder.cpp.o
[ 78%] Building CXX object CMakeFiles/objects.dir/src/v1_encoder.cpp.o
[ 79%] Building CXX object CMakeFiles/objects.dir/src/v2_decoder.cpp.o
[ 80%] Building CXX object CMakeFiles/objects.dir/src/v2_encoder.cpp.o
[ 81%] Building CXX object CMakeFiles/objects.dir/src/xpub.cpp.o
[ 82%] Building CXX object CMakeFiles/objects.dir/src/xsub.cpp.o
[ 83%] Building CXX object CMakeFiles/objects.dir/src/zmq.cpp.o
[ 84%] [ 85%] Building CXX object CMakeFiles/objects.dir/src/zmq_utils.cpp.o
Building CXX object CMakeFiles/objects.dir/src/decoder_allocators.cpp.o
[ 86%] Building CXX object CMakeFiles/objects.dir/src/socket_poller.cpp.o
[ 87%] Building CXX object CMakeFiles/objects.dir/src/timers.cpp.o
[ 88%] Building CXX object CMakeFiles/objects.dir/src/radio.cpp.o
[ 89%] Building CXX object CMakeFiles/objects.dir/src/dish.cpp.o
[ 90%] Building CXX object CMakeFiles/objects.dir/src/udp_engine.cpp.o
[ 91%] Building CXX object CMakeFiles/objects.dir/src/udp_address.cpp.o
[ 92%] Building CXX object CMakeFiles/objects.dir/src/scatter.cpp.o
[ 93%] Building CXX object CMakeFiles/objects.dir/src/gather.cpp.o
[ 94%] Building CXX object CMakeFiles/objects.dir/src/ip_resolver.cpp.o
[ 95%] Building CXX object CMakeFiles/objects.dir/src/zap_client.cpp.o
[ 96%] Building CXX object CMakeFiles/objects.dir/src/stream_connecter_base.cpp.o
[ 97%] Building CXX object CMakeFiles/objects.dir/src/stream_listener_base.cpp.o
[ 98%] Building CXX object CMakeFiles/objects.dir/src/tipc_address.cpp.o
[ 99%] Building CXX object CMakeFiles/objects.dir/src/tipc_connecter.cpp.o
[100%] Building CXX object CMakeFiles/objects.dir/src/tipc_listener.cpp.o
gmake[3]: Leaving directory `/home/handler/zeromq-install-test/node_modules/zeromq/build/libzmq'
[100%] Built target objects
gmake[3]: Entering directory `/home/handler/zeromq-install-test/node_modules/zeromq/build/libzmq'
Scanning dependencies of target libzmq-static
gmake[3]: Leaving directory `/home/handler/zeromq-install-test/node_modules/zeromq/build/libzmq'
gmake[3]: Entering directory `/home/handler/zeromq-install-test/node_modules/zeromq/build/libzmq'
Linking CXX static library lib/libzmq.a
gmake[3]: Leaving directory `/home/handler/zeromq-install-test/node_modules/zeromq/build/libzmq'
[100%] Built target libzmq-static
gmake[2]: Leaving directory `/home/handler/zeromq-install-test/node_modules/zeromq/build/libzmq'
Install the project...
-- Install configuration: "Release"
-- Installing: /home/handler/zeromq-install-test/node_modules/zeromq/build/libzmq/lib/pkgconfig/libzmq.pc
-- Installing: /home/handler/zeromq-install-test/node_modules/zeromq/build/libzmq/include/zmq.h
-- Installing: /home/handler/zeromq-install-test/node_modules/zeromq/build/libzmq/include/zmq_utils.h
-- Installing: /home/handler/zeromq-install-test/node_modules/zeromq/build/libzmq/share/zmq/AUTHORS.txt
-- Installing: /home/handler/zeromq-install-test/node_modules/zeromq/build/libzmq/share/zmq/COPYING.txt
-- Installing: /home/handler/zeromq-install-test/node_modules/zeromq/build/libzmq/share/zmq/COPYING.LESSER.txt
-- Installing: /home/handler/zeromq-install-test/node_modules/zeromq/build/libzmq/share/zmq/NEWS.txt
-- Installing: /home/handler/zeromq-install-test/node_modules/zeromq/build/libzmq/share/cmake/ZeroMQ/ZeroMQTargets.cmake
-- Installing: /home/handler/zeromq-install-test/node_modules/zeromq/build/libzmq/share/cmake/ZeroMQ/ZeroMQTargets-release.cmake
-- Installing: /home/handler/zeromq-install-test/node_modules/zeromq/build/libzmq/share/cmake/ZeroMQ/ZeroMQConfig.cmake
-- Installing: /home/handler/zeromq-install-test/node_modules/zeromq/build/libzmq/share/cmake/ZeroMQ/ZeroMQConfigVersion.cmake
gmake[1]: Leaving directory `/home/handler/zeromq-install-test/node_modules/zeromq/build/libzmq'
  TOUCH Release/obj.target/libzmq.stamp
  CXX(target) Release/obj.target/zeromq/src/context.o
g++: error: unrecognized command line option ‘-std=c++17’
make: *** [Release/obj.target/zeromq/src/context.o] Error 1
make: Leaving directory `/home/handler/zeromq-install-test/node_modules/zeromq/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:193:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 3.10.0-957.27.2.el7.x86_64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/handler/zeromq-install-test/node_modules/zeromq
gyp ERR! node -v v10.17.0
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**Expected behavior**

Build ZeroMQ bindings without errors.

**Tested on**
 - OS: CentOS 7.6
 - ZeroMQ.js version: 6.0.0-beta.4

**Comment by rolftimmermans** [comment]
The prebuild for Linux x64 does not work on CentOS 7 because it does not have some symbols emitted by GCC. Specifically `GLIBCXX_3.4.20` and `GLIBCXX_3.4.21`. I tried compiling libzmq with `_GLIBCXX_USE_CXX11_ABI=0` but even that leaves a reference to `_ZSt24__throw_out_of_range_fmtPKcz@@GLIBCXX_3.4.20`. So the prebuilds are a bit of a dead end on CentOS 7.

Compiling the bindings on the host machine is a viable alternative, but it requires a C++17 capable compiler. In the case of GCC it should be at least GCC 7. It's possible to install one on CentOS, perhaps somewhat like this:
```yum install centos-release-scl
yum install install devtoolset-7-gcc
scl enable devtoolset-7 bash
which gcc
gcc --version```

FWIW the prebuild does seem to work on CentOS 8.

**Comment by rolftimmermans** [comment]
I have added more details to the supported platforms in the README. I think supporting CentOS 7 with prebuilt binaries is too difficult for us at the moment. On Travis it would require compiling with Ubuntu `trusty`, which is EOL. Additionally we'd have to strip out all code based on C++14/17 features.

It should be more straightforward to install the dependencies required to build from source with the `devtoolset-7-gcc` package and install `zeromq` from source. Hope that helps!

**Comment by ezze** [comment]
@rolftimmermans, thanks for looking at it and providing a solution.

Changing GCC compiler to a fresh version works for me:

```
[handler@node06 zeromq-install-test]$ gcc --version
gcc (GCC) 8.3.1 20190311 (Red Hat 8.3.1-3)
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[handler@node06 zeromq-install-test]$ yarn add zeromq@^6.0.0-beta.4 --build-from-source
yarn add v1.17.3
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 3 new dependencies.
info Direct dependencies
└─ zeromq@6.0.0-beta.4
info All dependencies
├─ node-addon-api@1.7.1
├─ node-gyp-build@4.2.0
└─ zeromq@6.0.0-beta.4
Done in 24.69s.
```

But will `--build-from-source` argument make sense when installing dependencies from `yarn.lock` on other machines? Or should I also run `yarn add zeromq@^6.0.0-beta.4 --build-from-source` during an installation there?

**yarn.lock**

```
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


node-addon-api@^1.7.1:
  version "1.7.1"
  resolved "https://registry.yarnpkg.com/node-addon-api/-/node-addon-api-1.7.1.tgz#cf813cd69bb8d9100f6bdca6755fc268f54ac492"
  integrity sha512-2+DuKodWvwRTrCfKOeR24KIc5unKjOh8mz17NCzVnHWfjAdDqbfbjqh7gUT+BkXBRQM52+xCHciKWonJ3CbJMQ==

node-gyp-build@^4.1.0:
  version "4.2.0"
  resolved "https://registry.yarnpkg.com/node-gyp-build/-/node-gyp-build-4.2.0.tgz#2c2b05f461f4178641a6ce2d7159f04094e9376d"
  integrity sha512-4oiumOLhCDU9Rronz8PZ5S4IvT39H5+JEv/hps9V8s7RSLhsac0TCP78ulnHXOo8X1wdpPiTayGlM1jr4IbnaQ==

zeromq@^6.0.0-beta.4:
  version "6.0.0-beta.4"
  resolved "https://registry.yarnpkg.com/zeromq/-/zeromq-6.0.0-beta.4.tgz#c58dc695a1c18fc6e3ff9fc0f82bf4047086e2ca"
  integrity sha512-PJYH5onBs8FE86wlLLGMXgxrF8ThQHuRpcjdsNKS2KVPf64679iiOLGsofV4ySD8rkEom40vYuzVqkMpe5FJQw==
  dependencies:
    node-addon-api "^1.7.1"
    node-gyp-build "^4.1.0"
```

**Comment by rolftimmermans** [comment]
The prebuilt binary is tested during installation, and if it doesn't work the build process will be started automatically, so no options need to be provided in this case.
