### ISSUE TITLE
Integration tests written with Jest are broken when ZeroMQ.js is added to the project

### ISSUE THREAD

**Issue by ezze** [zeromq/zeromq.js#366]
**Describe the bug**

I added and used ZeroMQ in my Node.js application. To be exact, `Request` and `Reply` instances are created in the source code. After that integration tests written with Jest are broken. Here is output sample of my CI pipeline:

```
$ yarn test:integration
yarn run v1.19.1
$ cross-env INTEGRATION=integration GDAL_DATA=node_modules/gdal/deps/libgdal/gdal/data jest --config jest.config.js --runInBand --verbose
PASS test/integration/product/ProductManager.test.js (16.596s)
  ProductManager
    ✓ add RAW product (173ms)
    ✓ add tamarin L0 product (487ms)
    ✓ add external L0 product (85ms)

FAIL test/integration/common/factory.test.js
  ● Test suite failed to run

    TypeError: Cannot redefine property: emitter
        at Function.defineProperty (<anonymous>)

    > 1 | import { Request, Reply } from 'zeromq';
        | ^
      2 | 
      3 | import EventBus from './EventBus';
      4 | 

      at Object.<anonymous> (node_modules/zeromq/lib/index.js:41:8)
      at Object.<anonymous> (src/events/AdvancedEventBus.js:1:1)
      at Object.<anonymous> (src/events/index.js:2:1)
      at Object.<anonymous> (src/common/factory.js:10:1)
      at Object.<anonymous> (test/integration/common/factory.test.js:6:1)
      at Promise._execute (node_modules/bluebird/js/release/debuggability.js:411:9)
      at Promise._resolveFromExecutor (node_modules/bluebird/js/release/promise.js:518:18)
      at new Promise (node_modules/bluebird/js/release/promise.js:103:10)
      at tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromiseCtx (node_modules/bluebird/js/release/promise.js:641:10)
      at _drainQueueStep (node_modules/bluebird/js/release/async.js:97:12)
      at _drainQueue (node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (node_modules/bluebird/js/release/async.js:15:14)

Test Suites: 1 failed, 1 passed, 2 total
Tests:       3 passed, 3 total
Snapshots:   0 total
Time:        18.069s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Reproducing**

Such kind of errors has already been [reported](https://github.com/facebook/jest/issues/8373) to Jest team but it was related to another library. I'm not sure whether I should report it there again or here first. If a repo to reproduce the issue with ZeroMQ is required I will consider to find a time to do that. But as you can see from Jest issue and my output above it's enough to require `Request` or `Reply` in two separate test files. Tests from the first file will pass, while the second one will throw the error:

```
 TypeError: Cannot redefine property: emitter
        at Function.defineProperty (<anonymous>)
```

**Expected behavior**

Run Jest tests without errors.

**Tested on**
 - OS: Ubuntu 18.04
 - ZeroMQ.js version: 6.0.0-beta.4

**Comment by rolftimmermans** [comment]
That makes sense, Jest runs the code for included files for each individual file. I don't see a fundamental problem working around that issue. It should be fixed by ba512b.

**Comment by ezze** [comment]
@rolftimmermans, thanks. Waiting for it being published in the next release.

**Comment by rolftimmermans** [comment]
Beta 5 has been released!

**Comment by ezze** [comment]
@rolftimmermans, thank you so much! Works for me!
