### ISSUE TITLE
Socket is busy writing; only one send operation may be in progress at any time

### ISSUE THREAD

**Issue by nodesocket** [zeromq/zeromq.js#427]
Running `6.0.0-beta.6` on `Node v12.18.3` on `Ubuntu 18.04`.

```javascript
Error: Socket is busy writing; only one send operation may be in progress at any time
    at Publisher.send (<anonymous>)
    at WebsocketClient.<anonymous> (/home/node/macd/crypto-ingestd/lib/CoinbaseProStreams.js:76:23)
    at WebsocketClient.emit (events.js:315:20)
    at WebsocketClient.onMessage (/home/node/macd/node_modules/coinbase-pro/lib/clients/websocket.js:94:12)
    at WebSocket.emit (events.js:315:20)
    at Receiver._receiver.onmessage (/home/node/macd/node_modules/ws/lib/websocket.js:137:47)
    at Receiver.dataMessage (/home/node/macd/node_modules/ws/lib/receiver.js:409:14)
    at Receiver.getData (/home/node/macd/node_modules/ws/lib/receiver.js:347:12)
    at Receiver.startLoop (/home/node/macd/node_modules/ws/lib/receiver.js:143:16)
    at Receiver.add (/home/node/macd/node_modules/ws/lib/receiver.js:117:10) {
  errno: 16,
  code: 'EBUSY'
}
```

Code example:

```javascript
const publisher = new zmq.Publisher({
    sendHighWaterMark: 1,
    sendTimeout: 0,
    heartbeatInterval: 10000,
});

publisher.bind('tcp://127.0.0.1:3030');

// on Etherum price ticks (many per second)
publisher.send(['eth-ticks', doc])
    .catch(Log.error);
```

**Comment by 8secz-johndpope** [comment]
me too. / same version
I can free up port momentarily by killing the zombie zmq 

 ./killZmq-staging.sh
```shell
#!/bin/bash
echo '🏗 freeing up node on port 3030/38333'
pid=$(lsof -t -i:28333,38333);set -f;a=(${pid})
for e in ${a[@]}
do
    echo $e
    kill -9 $e
done


```

**Comment by nodesocket** [comment]
@8secz-johndpope were you setting `sendHighWaterMark: 1` as well?

**Comment by 8secz-johndpope** [comment]
No - that was just throwing code at the wall. it really was a case of the code incorrectly throwing 2 pushes (kind of in some async yet simultaneous edge case). My logic is app is supposed to do one push for a health check the exit out. That may not help your use case.

**Comment by nodesocket** [comment]
Migrated to using `Push()` and `Pull()` instead of `Publisher()`.
