### ISSUE TITLE
Install fails with node v14.15.0

### ISSUE THREAD

**Issue by JamesRamm** [zeromq/zeromq.js#430]
**Describe the bug**
Installing the 5.x version fails with Node version 14.15.0 (LTS).

Log:
```bash
../binding.cc: In static member function 'static Nan::NAN_METHOD_RETURN_TYPE zmq::Socket::Monitor(Nan::NAN_METHOD_ARGS_TYPE)':
../binding.cc:1122:103: warning: cast between incompatible function types from 'void (*)(uv_timer_t*, int)' {aka 'void (*)(uv_timer_s*, int)'} to 'uv_timer_cb' {aka 'void (*)(uv_timer_s*)'} [-Wcast-function-type]
 1122 |       uv_timer_start(socket->monitor_handle_, reinterpret_cast<uv_timer_cb>(Socket::UV_MonitorCallback), timer_interval, 0);
      |                                                                                                       ^
../binding.cc: In static member function 'static Nan::NAN_METHOD_RETURN_TYPE zmq::Socket::Sendv(Nan::NAN_METHOD_ARGS_TYPE)':
../binding.cc:1300:39: error: no matching function for call to 'v8::Array::Get(uint32_t&)'
 1300 |       Local<Object> buf = batch->Get(i).As<Object>();
      |                                       ^
In file included from ../binding.cc:24:
/root/.cache/node-gyp/14.15.0/include/node/v8.h:3717:43: note: candidate: 'v8::MaybeLocal<v8::Value> v8::Object::Get(v8::Local<v8::Context>, v8::Local<v8::Value>)'
 3717 |   V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
      |                                           ^~~
/root/.cache/node-gyp/14.15.0/include/node/v8.h:3717:43: note:   candidate expects 2 arguments, 1 provided
/root/.cache/node-gyp/14.15.0/include/node/v8.h:3720:43: note: candidate: 'v8::MaybeLocal<v8::Value> v8::Object::Get(v8::Local<v8::Context>, uint32_t)'
 3720 |   V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
      |                                           ^~~
/root/.cache/node-gyp/14.15.0/include/node/v8.h:3720:43: note:   candidate expects 2 arguments, 1 provided
../binding.cc:1300:50: error: expected primary-expression before '>' token
 1300 |       Local<Object> buf = batch->Get(i).As<Object>();
      |                                                  ^
../binding.cc:1300:52: error: expected primary-expression before ')' token
 1300 |       Local<Object> buf = batch->Get(i).As<Object>();
      |                                                    ^
../binding.cc:1301:48: error: no matching function for call to 'v8::Array::Get(uint32_t)'
 1301 |       Local<Number> flagsObj = batch->Get(i + 1).As<Number>();
      |                                                ^
In file included from ../binding.cc:24:
/root/.cache/node-gyp/14.15.0/include/node/v8.h:3717:43: note: candidate: 'v8::MaybeLocal<v8::Value> v8::Object::Get(v8::Local<v8::Context>, v8::Local<v8::Value>)'
 3717 |   V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
      |                                           ^~~
/root/.cache/node-gyp/14.15.0/include/node/v8.h:3717:43: note:   candidate expects 2 arguments, 1 provided
/root/.cache/node-gyp/14.15.0/include/node/v8.h:3720:43: note: candidate: 'v8::MaybeLocal<v8::Value> v8::Object::Get(v8::Local<v8::Context>, uint32_t)'
 3720 |   V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
      |                                           ^~~
/root/.cache/node-gyp/14.15.0/include/node/v8.h:3720:43: note:   candidate expects 2 arguments, 1 provided
../binding.cc:1301:59: error: expected primary-expression before '>' token
 1301 |       Local<Number> flagsObj = batch->Get(i + 1).As<Number>();
      |                                                           ^
../binding.cc:1301:61: error: expected primary-expression before ')' token
 1301 |       Local<Number> flagsObj = batch->Get(i + 1).As<Number>();
      |                                                             ^
In file included from ../binding.cc:25:
../binding.cc: At global scope:
/root/.cache/node-gyp/14.15.0/include/node/node.h:758:43: warning: cast between incompatible function types from 'void (*)(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)' {aka 'void (*)(v8::Local<v8::Object>)'} to 'node::addon_register_func' {aka 'void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)'} [-Wcast-function-type]
  758 |       (node::addon_register_func) (regfunc),                          \
      |                                           ^
/root/.cache/node-gyp/14.15.0/include/node/node.h:792:3: note: in expansion of macro 'NODE_MODULE_X'
  792 |   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
      |   ^~~~~~~~~~~~~
../binding.cc:1558:1: note: in expansion of macro 'NODE_MODULE'
 1558 | NODE_MODULE(zmq, init)
      | ^~~~~~~~~~~
In file included from ../binding.cc:24:
/root/.cache/node-gyp/14.15.0/include/node/v8.h: In instantiation of 'void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = node::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)]':
/root/.cache/node-gyp/14.15.0/include/node/node_object_wrap.h:85:78:   required from here
/root/.cache/node-gyp/14.15.0/include/node/v8.h:10867:16: warning: cast between incompatible function types from 'v8::WeakCallbackInfo<node::ObjectWrap>::Callback' {aka 'void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)'} to 'Callback' {aka 'void (*)(const v8::WeakCallbackInfo<void>&)'} [-Wcast-function-type]
10867 |                reinterpret_cast<Callback>(callback), type);
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/.cache/node-gyp/14.15.0/include/node/v8.h: In instantiation of 'void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)]':
../../nan/nan_object_wrap.h:65:61:   required from here
/root/.cache/node-gyp/14.15.0/include/node/v8.h:10867:16: warning: cast between incompatible function types from 'v8::WeakCallbackInfo<Nan::ObjectWrap>::Callback' {aka 'void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)'} to 'Callback' {aka 'void (*)(const v8::WeakCallbackInfo<void>&)'} [-Wcast-function-type]
make: *** [zmq.target.mk:111: Release/obj.target/zmq/binding.o] Error 1
make: Leaving directory '/node_modules/zeromq/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Linux 5.8.0-7625-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /node_modules/zeromq
gyp ERR! node -v v14.15.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
```

**Reproducing**
`npm install zeromq@5.1.0` with the LTS version of NodeJS.
The package manager does not particularly matter - I can reproduce with yarn & pnpm also. 

**Expected behavior**
The current LTS version of NodeJS is v14.x and v5.x is still the stable release of zeromq, so I would expect it to install without issue. We (and no doubt many other companies) keep our NodeJS installs in sync with the LTS releases and this is a major blocker for us right now. 

**Tested on**
 - OS: Ubuntu 20.04, 18.04, alpine3.12, debian 10.6
 - ZeroMQ.js version: 5.1.0

**Comment by wa1one** [comment]
+1

**Comment by jacany** [comment]
I am also having this issue.

**Comment by JamesRamm** [comment]
@aminya 
I saw that there has been some recent releases (v5.2.6-8) that may fix this issue - is that the idea/can you confirm?

**Comment by aminya** [comment]
Yes, this issue is already fixed with the latest v5 release.

**Comment by Alireza17224** [comment]
Same issue here
