### ISSUE TITLE
Subscribing does not work

### ISSUE THREAD

**Issue by gastmeier** [zeromq/zeromq.js#456]
.

**Comment by gastmeier** [comment]
I have to go through the unit tests to find pieces of what i am able to put into the subscribe method. Then i use code of these tests and it does not work. Same error.

```
socket.on('close', function() {
});
```

**Comment by gastmeier** [comment]
When i copy more code of the unit tests, this code does not work.

```
socket.setsockopt(zeromq.ZMQ_RECONNECT_IVL, 5)
```

```
Error: Invalid argument
    at exports.Socket._subscribe (/.../node_modules/zeromq/lib/index.js:413:22)
    at exports.Socket.Socket.subscribe (/.../node_modules/zeromq/lib/index.js:591:19)
    at Object.<anonymous> (/.../src/rcon.ts:9:8)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Module.m._compile (/.../node_modules/ts-node/src/index.ts:1056:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Object.require.extensions.<computed> [as .ts] (/.../node_modules/ts-node/src/index.ts:1059:12)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
```

Can you tell me why this is even a possibility? I don't get it. Are the tests out of sync with the code?

**Comment by gastmeier** [comment]
Here is my next try. I just want to show to you what kind of idiotic things i have to do. I am trying to find out if there is also the possibility of valid arguments of this subscribe function.

```
for (let i=0; i<10000000; i++) {
  let error = false
  try {
    socket.subscribe('' + i)
  }
  catch (e) {
    error = true
  }    

  if (! error) {
    console.log(i)
  }
}
```

Should programming be like that?
