### ISSUE TITLE
TypeError: zmq.Reply is not a constructor

### ISSUE THREAD

**Issue by signalarun** [zeromq/zeromq.js#500]
**Describe the bug**
I am using  "zeromq": "^5.2.8"  with example code given here https://zeromq.org/get-started/?language=nodejs&library=zeromqjs#
```
const sock = new zmq.Reply();
               ^

TypeError: zmq.Reply is not a constructor
    at runServer (/media/bluebird/Data/WORKSPACE/WORKSPACE_STDC/WORKSPACE_NPOL/WORKSPACE_MEMORY_QUEUE/Sample/zeromq-helloworld/server.js:12:16)
    at Object.<anonymous> (/media/bluebird/Data/WORKSPACE/WORKSPACE_STDC/WORKSPACE_NPOL/WORKSPACE_MEMORY_QUEUE/Sample/zeromq-helloworld/server.js:23:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47
```
but upon running, getting following 
**Reproducing**
```
const zmq = require('zeromq');

async function runServer() {
  
  const sock = new zmq.Reply();

  await sock.bind('tcp://*:5555');

  for await (const [msg] of sock) {
    console.log('Received ' + ': [' + msg.toString() + ']');
    await sock.send('World');
    // Do some 'work'
  }
}

runServer();

```

**Expected behavior**
Should wait for client connection

**Tested on**
 -  Ubuntu 20.04]
 - ZeroMQ.js version: ["^5.2.8"]

**Comment by Famosi** [comment]
Did you managed to solve this?
