### ISSUE TITLE
CI: Test failure reporting fails

### ISSUE THREAD

**Issue by rotu** [zeromq/zeromq.js#625]
In CI, tests are failing, and the test reporter is crashing with "TypeError: test.titlePath is not a function"

e.g.: https://github.com/zeromq/zeromq.js/actions/runs/9551631841/job/26326410030#step:14:1026

```
/Users/runner/work/zeromq.js/zeromq.js/node_modules/.pnpm/mocha@10.4.0/node_modules/mocha/lib/reporters/base.js:286
  failures.forEach(function (test, i) {
           ^
TypeError: test.titlePath is not a function
    at /Users/runner/work/zeromq.js/zeromq.js/node_modules/.pnpm/mocha@10.4.0/node_modules/mocha/lib/reporters/base.js:327:10
    at Array.forEach (<anonymous>)
    at Function.exports.list (/Users/runner/work/zeromq.js/zeromq.js/node_modules/.pnpm/mocha@10.4.0/node_modules/mocha/lib/reporters/base.js:286:12)
    at Spec.Base.epilogue (/Users/runner/work/zeromq.js/zeromq.js/node_modules/.pnpm/mocha@10.4.0/node_modules/mocha/lib/reporters/base.js:426:10)
    at Object.onceWrapper (node:events:631:28)
    at ParallelBufferedRunner.emit (node:events:529:35)
    at ParallelBufferedRunner.emit (node:domain:489:12)
    at /Users/runner/work/zeromq.js/zeromq.js/node_modules/.pnpm/mocha@10.4.0/node_modules/mocha/lib/nodejs/parallel-buffered-runner.js:347:14
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
 ELIFECYCLE  Test failed. See above for more details.
Error: Final attempt failed. Child_process exited with error code 1
```
[logs_24997356421.zip](https://github.com/user-attachments/files/15875144/logs_24997356421.zip)

**Comment by aminya** [comment]
That's unexpected as it doesn't happen locally when running the tests.
