### ISSUE TITLE
Porting 5.3.0 to 6.0.4 subscribe code not working

### ISSUE THREAD

**Issue by fjdvchain** [zeromq/zeromq.js#653]
**Describe the bug** Moving example code from 5.3.0 to 6.0.4 is causing an error

**Reproducing**
Code for version 5.3.0

```ts
import zmq from 'zeromq'

async function main() {
  console.log('here')
  let sub = zmq.socket("sub");

  await sub.connect("tcp://127.0.0.1:5555")
  sub.subscribe("FEED")
  console.log("Subscriber bound to port 5555")

  sub.on("message", (topic, zmq_message) => {
    console.log(topic, zmq_message.toString())
  })
}
```

code for version 6.0.4
```ts
import zmq from 'zeromq'

const main = async () => {
  const sock = new zmq.Subscriber()

  sock.connect("tcp://127.0.0.1:5555")
  sock.subscribe("FEED")
  console.log("Subscriber connected to port 3000")

  for await (const [topic, msg] of sock) {
    console.log(
      "received a message related to:",
      topic,
      "containing message:",
      msg,
    )
  }
}
```

**Expected behavior** 
I expected to receive messages on v6.0.4 similar to how I receive messages on 5.3.0 but instead I get this error message

```sh
TypeError: Cannot read properties of undefined (reading 'Subscriber')
    at main (/src/zmq.ts:2:950)
    at /src/zmq.ts:2:1203
    at Object.<anonymous> (/src/zmq.ts:3:3)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Object.S (/node_modules/tsx/dist/cjs/index.cjs:1:1292)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at cjsLoader (node:internal/modules/esm/translators:348:17)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:297:7)
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)

Node.js v20.16.0
```

**Tested on**

- OS: [e.g. Macbook Pro M3 Sonoma 14.5]
- ZeroMQ.js version: [5.3.0, 6.0.4]

**Comment by fjdvchain** [comment]
okay so turns out I cannot import default like this
```ts
import zeromq from 'zeromq'
```

instead this works fine
```ts
import { Subscriber } from 'zeromq'
```

I feel like this is still an issue...

**Comment by aminya** [comment]
Yes, you have to use it properly named ES module imports. We have to update the readme and the examples to ES modules.

**Comment by fjdvchain** [comment]
issue resolved. pending on README and documentation updates
