### ISSUE TITLE
Cannot install via NPM on Windows machine.

### ISSUE THREAD

**Issue by Amirali-Amirifar** [zeromq/zeromq.js#656]
**Describe the bug** Upon installation using `npm install zeromq` throws `error code 3221225477` and halts the installation.
Although installation works as normal on an ubuntu machine.

**Logs** 
```
81 info run zeromq@6.0.4 install { code: 3221225477, signal: null }
82 verbose stack Error: command failed
82 verbose stack     at promiseSpawn (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\promise-spawn\lib\index.js:22:22)
82 verbose stack     at spawnWithShell (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\promise-spawn\lib\index.js:124:10)
82 verbose stack     at promiseSpawn (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\promise-spawn\lib\index.js:12:12)
82 verbose stack     at runScriptPkg (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\run-script\lib\run-script-pkg.js:77:13)
82 verbose stack     at runScript (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\run-script\lib\run-script.js:9:12)
82 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\rebuild.js:329:17
82 verbose stack     at run (C:\Program Files\nodejs\node_modules\npm\node_modules\promise-call-limit\dist\commonjs\index.js:67:22)
82 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\promise-call-limit\dist\commonjs\index.js:84:9
82 verbose stack     at new Promise (<anonymous>)
82 verbose stack     at callLimit (C:\Program Files\nodejs\node_modules\npm\node_modules\promise-call-limit\dist\commonjs\index.js:35:69)
83 verbose pkgid zeromq@6.0.4
84 error code 3221225477
85 error path C:\[__PATH__]\node_modules\zeromq
86 error command failed
87 error command C:\Windows\system32\cmd.exe /d /s /c cross-env npm_config_build_from_source=true aminya-node-gyp-build
88 silly unfinished npm timer reify 1726584768029
89 silly unfinished npm timer reify:build 1726584769098
90 silly unfinished npm timer build 1726584769098
91 silly unfinished npm timer build:deps 1726584769099
92 silly unfinished npm timer build:run:install 1726584769116
93 silly unfinished npm timer build:run:install:node_modules/zeromq 1726584769117

95 verbose os Windows_NT 10.0.22000
96 verbose node v20.17.0
97 verbose npm  v10.8.2
```
**Tried** increase node access permissions.

- OS: Windows 11 64bit
- ZeroMQ.js version: latest

**Comment by aminya** [comment]
This sounds like a missing DLL issue. Do you have Visual C++ redistributable installed?

**Comment by Amirali-Amirifar** [comment]
Solved the issue, thank you.

**Comment by dmos62** [comment]
node-gyp has Windows-specific instructions https://github.com/nodejs/node-gyp/blob/main/README.md#on-windows
