### ISSUE TITLE
Distribution File Download... Generic error occured ZlibError: zlib: incorrect header check

### ISSUE THREAD

**Issue by diefbell-grabcad** [zeromq/zeromq.js#677]
On Windows 10, building v6 for Electron (from within the repo itself, using `cmake-ts` WITHOUT the `nativeonly` argument).

Getting the error:
```
Found generator:  Visual Studio 17 2022
running in xyz\zeromq.js command []
> Setting up staging directory... [ DONE ]
---------------- BEGIN CONFIG ----------------
> Distribution File Download... Generic error occured ZlibError: zlib: incorrect header check
    at Gunzip.write (C:\xyz\cmake-ts\node_modules\minizlib\index.js:154:22)
    at Request.ondata (node:internal/streams/legacy:21:31)
    at Request.emit (node:events:531:35)
    at IncomingMessage.<anonymous> (C:\xyz\cmake-ts\node_modules\@cypress\request\request.js:1067:12)
    at IncomingMessage.emit (node:events:519:28)
    at Readable.read (node:internal/streams/readable:780:10)
    at flow (node:internal/streams/readable:1281:53)
    at resume_ (node:internal/streams/readable:1260:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'Z_DATA_ERROR',
  errno: -3
  ```

Completely fresh, no `staging` folder.

Edit 1: A bit more of an investigation suggests it's happening in `download.ts` inside of `@aminya/cmake-ts`.

Edit 2: It seems that GitHub have removed `atom.io`, which is where the Electron libs where downloaded from. Attempting to find new ones...

Edit 3: Found new ones, trying to work out migration steps: https://www.electronjs.org/blog/s3-bucket-change. I'm not sure if all of the headers for the `include` folder are available somewhere, but this JSON file has a map of all Electron versions to their respective Node versions: https://releases.electronjs.org/releases.json

**Comment by diefbell-grabcad** [comment]
Created a PR for this fix in `@aminya/cmake-ts`: https://github.com/aminya/cmake-ts/pull/3

**Comment by diefbell-grabcad** [comment]
Closing since PR is for cmake-ts, not this repo
